TastyKitchen.Web.UI/Controllers/DailySaleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Neubel.Wow.Win.Authentication.Core.Interfaces.TastyKitchen;
using Neubel.Wow.Win.Authentication.Core.Model.TastyKitchen;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using TastyKitchen.Web.UI.Models;

namespace TastyKitchen.Web.UI.Controllers
{
    [Authorize]
    public class DailySaleController : Controller
    {
        private readonly ILogger<DailySaleController> _logger;
        private readonly IDailySaleService _dailySaleService;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public DailySaleController(ILogger<DailySaleController> logger, IDailySaleService dailySaleService, IWebHostEnvironment hostingEnvironment)
        {
            _logger = logger;
            _dailySaleService = dailySaleService;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        [Authorize(Roles = "Sysadmin,Admin,Manager")]
        public IActionResult Index()
        {
            var sales = _dailySaleService.GetPages(1);

            List<Models.DailySale> dailySales = new List<Models.DailySale>();

            foreach (var item in sales)
            {
                dailySales.Add(new Models.DailySale { Id = item.Id, Amount = item.Amount, Date = item.Date, BillNumber = item.BillNumber, SaleType = item.Type });
            }
            ViewBag.nextPage = 2;
            ViewBag.PreviousPage = 0;
            return View(dailySales.AsEnumerable());
        }

        [HttpPost]
        [Authorize(Roles = "Sysadmin,Admin,Manager")]
        public IActionResult Index(int pageIndex)
        {
            var expenses = _dailySaleService.GetPages(pageIndex);

            List<Models.DailySale> dailySales = new List<Models.DailySale>();

            foreach (var item in expenses)
            {
                dailySales.Add(new Models.DailySale { Id = item.Id, Amount = item.Amount, Date = item.Date, BillNumber = item.BillNumber, SaleType = item.Type });
            }
            ViewBag.nextPage = pageIndex + 1;
            ViewBag.PreviousPage = pageIndex == 1 ? 1 : pageIndex - 1;
            return View(dailySales.AsEnumerable());
        }

        [HttpGet]
        [Authorize(Roles = "Sysadmin,Admin,Manager")]
        public IActionResult Create()
        {
            return View(new Models.DailySale { Date = DateTime.Now });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Sysadmin,Admin,Manager")]
        public IActionResult Create([Bind] Models.DailySale dailySale)
        {
            if (ModelState.IsValid)
            {
                var dailySaleBusinessModel = new Neubel.Wow.Win.Authentication.Core.Model.TastyKitchen.DailySale
                {
                    Date = dailySale.Date,
                    Amount = dailySale.Amount,
                    Id = dailySale.Id,
                    BillNumber = dailySale.BillNumber,
                    Type = dailySale.SaleType
                };

                _dailySaleService.Add(dailySaleBusinessModel);

                return RedirectToAction("Index");
            }
            return View(dailySale);
        }

        [HttpGet]
        [Authorize(Roles = "Sysadmin,Admin,Manager")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = _dailySaleService.Get((int)id);

            if (sale == null)
            {
                return NotFound();
            }

            var expenseUIModel = new Models.DailySale
            {
                Date = sale.Date,
                Amount = sale.Amount,
                Id = sale.Id,
                BillNumber = sale.BillNumber,
                SaleType = sale.Type
            };

            return View(expenseUIModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Sysadmin,Admin,Manager")]
        public IActionResult Edit(int id, [Bind] Models.DailySale dailySale)
        {
            if (id != dailySale.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                var expenseBusinessModel = new Neubel.Wow.Win.Authentication.Core.Model.TastyKitchen.DailySale
                {
                    Date = dailySale.Date,
                    Amount = dailySale.Amount,
                    Id = dailySale.Id,
                    BillNumber = dailySale.BillNumber,
                    Type = dailySale.SaleType
                };

                _dailySaleService.Update(id, expenseBusinessModel);

                return RedirectToAction("Index");
            }
            return View(dailySale);
        }

        [HttpGet]
        [Authorize(Roles = "Sysadmin,Admin,Manager")]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = _dailySaleService.Get((int)id);

            if (sale == null)
            {
                return NotFound();
            }

            var saleUIModel = new Models.DailySale
            {
                Date = sale.Date,
                Amount = sale.Amount,
                Id = sale.Id,
                BillNumber = sale.BillNumber,
                SaleType = sale.Type
            };

            return View(saleUIModel);
        }

        [HttpGet]
        [Authorize(Roles = "Sysadmin,Admin,Manager")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var sale = _dailySaleService.Get((int)id);


            if (sale == null)
            {
                return NotFound();
            }


            var saleUIModel = new Models.DailySale
            {
                Date = sale.Date,
                Amount = sale.Amount,
                Id = sale.Id,
                BillNumber = sale.BillNumber,
                SaleType = sale.Type
            };
            return View(saleUIModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Sysadmin,Admin,Manager")]
        public IActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            _dailySaleService.Delete((int)id);
            return RedirectToAction("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        [Authorize(Roles = "Sysadmin,Admin")]
        public IActionResult ExportToExcel()
        {
            List<DailySaleExcelDTO> resultsDTO = new List<DailySaleExcelDTO>();
            var results = _dailySaleService.Get();
            foreach (var item in results)
            {
                resultsDTO.Add(new DailySaleExcelDTO
                {
                    Id = item.Id,
                    Amount = item.Amount,
                    Date = item.Date.ToString("MM/dd/yyyy hh:mm tt"),
                    SaleType = item.Type
                });
            }

            var stream = new MemoryStream();

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (var package = new ExcelPackage(stream))
            {
                var worksheet = package.Workbook.Worksheets.Add("Sheet1");
                worksheet.Cells.LoadFromCollection(resultsDTO, true);
                package.Save();
            }
            stream.Position = 0;
            string excelName = $"TastyKitchenSale-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx";
            return File(stream, "application/vdn.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
        }

        [HttpPost]
        [Authorize(Roles = "Sysadmin,Admin")]
        public IActionResult ImportFromExcel(IFormFile file)
        {
            
            if (file == null || file.Length == 0)
                return Content("File Not Selected");

            string fileExtension = Path.GetExtension(file.FileName);
            if (fileExtension != ".xls" && fileExtension != ".xlsx")
                return Content("File Not Selected");

            var rootFolder = _hostingEnvironment.WebRootPath;
            var fileName = file.FileName;
            var filePath = Path.Combine(rootFolder, "uploadedFiles", fileName);
            var fileLocation = new FileInfo(filePath);

            if (file.Length <= 0 && file.Length < (1000000 / 2)) // not more than 0.5 MB excel file)
                return BadRequest("File not found or size is more than specified limit");

            try
            {

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }

                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                using (ExcelPackage package = new ExcelPackage(fileLocation))
                {
                    ExcelWorksheet workSheet = package.Workbook.Worksheets["Sheet1"];
                    //var workSheet = package.Workbook.Worksheets.First();
                    int totalRows = workSheet.Dimension.Rows;

                    var dailySale = new List<Neubel.Wow.Win.Authentication.Core.Model.TastyKitchen.DailySale>();

TastyKitchen.Web.UI/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Neubel.Wow.Win.Authentication.Core.Interfaces.TastyKitchen;
using Neubel.Wow.Win.Authentication.Core.Model.TastyKitchen;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TastyKitchen.Web.UI.Models;

namespace TastyKitchen.Web.UI.Controllers
{
    [Authorize(Roles= "Sysadmin,Admin")]
    public class DashboardController : Controller
    {
        private readonly ILogger<DailySaleController> _logger;
        private readonly IDailySaleService _dailySaleService;
        private readonly IDailyExpenseService _dailyExpenseService;
        public DashboardController(ILogger<DailySaleController> logger, IDailySaleService dailySaleService, IDailyExpenseService dailyExpenseService)
        {
            _logger = logger;
            _dailySaleService = dailySaleService;
            _dailyExpenseService = dailyExpenseService;
        }
        // GET: DashboardController
        public ActionResult Index()
        {
            DashboardViewModel dashboard = new DashboardViewModel();
            var firstDayOfMonth = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);

            var firstDayOfPreviousMonth = firstDayOfMonth.AddMonths(-1);
            var lastDayOfPreviousMonth = firstDayOfPreviousMonth.AddMonths(1).AddDays(-1);
            List<BillWiseSaleReport> previousMonthSalesData = _dailySaleService.GetBillWiseSaleReport(firstDayOfPreviousMonth, lastDayOfPreviousMonth);
            var expense = _dailyExpenseService.Get(firstDayOfPreviousMonth, lastDayOfPreviousMonth);

            //Mapping to UI Model
            expense.ForEach(x =>
            {
                dashboard.TotalExpenseAmount += x.Amount;
            });

            previousMonthSalesData.ForEach(x => 
            { 
                dashboard.TotalSaleAmount += x.Amount;
                dashboard.TotalNoOfOrders += x.BillWiseSales.Count;
            });

            dashboard.AverageOrderAmountPerOrder = Math.Round(dashboard.TotalSaleAmount / dashboard.TotalNoOfOrders, 2);

            List<MenuItemWiseSaleReport> menuItemWiseSaleReports = _dailySaleService.GetMenuItemWiseSaleReport(firstDayOfPreviousMonth, lastDayOfPreviousMonth);

            var orderedMenuItems = menuItemWiseSaleReports.SelectMany(x => x.MenuItemWiseSales);

            var menuItemWiseTotalSaleDTO = orderedMenuItems.GroupBy(t => t.Name).Select(z =>
            new MenuItemWiseTotalSaleByAmountDTO
            {
                Name = z.Key,
                TotalAmount = z.Sum(s => s.Amount)
            }).OrderByDescending(o => o.TotalAmount).Take(30).ToList();
            dashboard.MenuItemWiseTotalSaleByAmountDTO = menuItemWiseTotalSaleDTO.ToArray();

            var menuItemWiseTotalSaleByQuantityDTO = orderedMenuItems.GroupBy(t => t.Name).Select(z =>
            new MenuItemWiseTotalSaleByQuantityDTO
            {
                Name = z.Key,
                TotalQuantity = z.Sum(s => s.Quantity)
            }).OrderByDescending(o => o.TotalQuantity).Take(30).ToList();
            dashboard.MenuItemWiseTotalSaleByQuantityDTO = menuItemWiseTotalSaleByQuantityDTO.ToArray();

            return View(dashboard);
        }

        // GET: DashboardController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DashboardController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DashboardController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DashboardController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DashboardController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DashboardController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DashboardController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

TastyKitchen.Web.UI/Controllers/SecurityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Neubel.Wow.Win.Authentication;
using Neubel.Wow.Win.Authentication.Common;
using Neubel.Wow.Win.Authentication.Core.Interfaces;
using Neubel.Wow.Win.Authentication.Core.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TastyKitchen.Web.UI.Models;

namespace TastyKitchen.Web.UI.Controllers
{
    public class SecurityController : Controller
    {
        private readonly IAuthenticationService _authenticationService;

        public SecurityController(IAuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginDTO loginRequest)
        {
            var loginReq = new LoginRequest { UserName = loginRequest.UserName, Password = loginRequest.Password };
            RequestResult<LoginToken> result = _authenticationService.Login(loginReq);

            if (result.IsSuccessful)
            {
                HttpContext.Session.SetString("Token", result.RequestedObject.AccessToken);

                return Json(new { status = true, message = "Login Successfull!" });
            }

            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult LoginOut()
        {
            HttpContext.Session.SetString("Token", null);

            return View();
        }

        //public ActionResult Validate(Admins admin)
        //{
        //    var _admin = db.Admins.Where(s => s.Email == admin.Email);
        //    if (_admin.Any())
        //    {
        //        if (_admin.Where(s => s.Password == admin.Password).Any())
        //        {

        //            return Json(new { status = true, message = "Login Successfull!" });
        //        }
        //        else
        //        {
        //            return Json(new { status = false, message = "Invalid Password!" });
        //        }
        //    }
        //    else
        //    {
        //        return Json(new { status = false, message = "Invalid Email!" });
        //    }
        //}
    }
}

TastyKitchen.Web.UI/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Tasty Kitchen</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Security" asp-action="Login"><span style="color:orangered; font-weight:bold">Tasty Kitchen</span></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Expense</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="DailySale" asp-action="Index">Sale</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Tasty Kitchen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
    </html>*@
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin Panel</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @*<link rel="stylesheet" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css">*@
    <link rel="stylesheet" href="~/dist/css/bootstrap.min.css">

    <!-- Morris chart -->
    @*<link rel="stylesheet" href="~/bower_components/morris.js/morris.css">*@
    <link rel="stylesheet" href="~/dist/css/morris.css">

    <!-- Font Awesome -->
    @*<link rel="stylesheet" href="~/bower_components/font-awesome/css/font-awesome.min.css">*@
    <link rel="stylesheet" href="~/dist/css/font-awesome.min.css">
    <!-- Ionicons -->
    @*<link rel="stylesheet" href="~/bower_components/Ionicons/css/ionicons.min.css">*@
    <link rel="stylesheet" href="~/dist/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/dist/css/skins/skin-black-light.min.css">
    <!-- jQuery 3 -->
    @*<script src="~/bower_components/jquery/dist/jquery.min.js"></script>*@
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <script src="~/dist/js/jquery.min.js"></script>
    @*<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>*@
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body class="hold-transition skin-black-light sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="~/Home/Index" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini" style="color:#f48a26;"><b>TKH</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg" style="color:#f48a26;"><b>Tasty Kitchen</b></span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="~/dist/img/logo_tk.png" class="user-image" alt="User Image">
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs" style="color:#f48a26;">Tasty Kitchen</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="~/dist/img/logo_tk.jpg" class="img-circle" alt="User Image">
                                    <p>
                                        <span style="color:#f48a26;font-weight:bold">Tasty Kitchen</span>
                                        <small style="color:#47f01e;">Swad Ghar ka</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Account</a>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/dist/img/logo_tk.png" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p style="color:#f48a26;">Tasty Kitchen</p>
                        <!-- Status -->
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form (Optional) -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- Sidebar Menu -->
                @Html.Partial("_MainMenu")
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            @RenderBody()
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <!-- Default to the left -->
            <strong> &copy; 2021 - Tasty Kitchen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>.</strong>  All rights reserved.
        </footer>

    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- Bootstrap 3.3.7 -->
    <script src="~/dist/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/admin-lte@3.1/dist/js/adminlte.min.js"></script>*@


    @RenderSection("Scripts", required: false)
</body>
</html>

TastyKitchen.Web.UI/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Tasty Kitchen</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Security" asp-action="Login"><span style="color:orangered; font-weight:bold">Tasty Kitchen</span></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Expense</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="DailySale" asp-action="Index">Sale</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Tasty Kitchen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
    </html>

TastyKitchen.Web.UI/Views/Shared/_MainMenu.cshtml
<ul class="sidebar-menu" data-widget="tree">
    <li class="header">HEADER</li>
    <!-- Optionally, you can add icons to the links -->
    <li class="active"><a href="~/Dashboard/Index"><i class="fa fa-bar-chart"></i> <span>Dashboard</span></a></li>
    <li><a href="~/Home/Index"><i class="fa fa-etsy"></i> <span>Expense</span></a></li>
    <li><a href="~/DailySale/Index"><i class="fa fa-skype"></i> <span>Sale</span></a></li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-indent"></i> <span>Multilevel</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="~/DailySale/Create">@*<i class="fa fa-dashboard"></i>*@ Add Daily Sale</a></li>
            <li><a href="~/Home/Create">@*<i class="fa fa-dashboard"></i>*@ Add Daily Expense</a></li>
        </ul>
    </li>
</ul>